services:
  - type: web
    name: api-eliofitness
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:clear
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=8080
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:tu-clave-generada
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: nombre_de_tu_bd
      - key: DB_USERNAME
        value: usuario
      - key: DB_PASSWORD
        value: contraseña
